[build-system]
requires = [
  "setuptools>=42",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-frontend = "build"
# Only build on CPython 3.8, 3.9 and 3.10
build = ["cp38-*", "cp39-*", "cp310-*"]
# Skip 32-bit builds
skip = ["*-win32", "*-manylinux_i686"]
